"""create film-genre association table

Revision ID: 21d327548e3a
Revises: 6ca30f52cc52
Create Date: 2025-05-27 19:03:41.430525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d327548e3a'
down_revision: Union[str, None] = '6ca30f52cc52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film_genre_assoc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], name=op.f('fk_film_genre_assoc_film_id_films'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_film_genre_assoc_genre_id_genres'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_film_genre_assoc')),
    sa.UniqueConstraint('film_id', 'genre_id', name=op.f('uq_film_genre_assoc_film_id_genre_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film_genre_assoc')
    # ### end Alembic commands ###
