"""create genres table

Revision ID: 6ca30f52cc52
Revises: d8fa1fcfab4c
Create Date: 2025-05-27 18:46:09.631049

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ca30f52cc52"
down_revision: Union[str, None] = "d8fa1fcfab4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genres",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "title",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.Text(),
            server_default="",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_genres")),
    )
    op.create_index(
        op.f("ix_genres_title"),
        "genres",
        ["title"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_genres_title"), table_name="genres")
    op.drop_table("genres")
    # ### end Alembic commands ###
